[build]
  command = "echo 'Node version:' && node --version && echo 'NPM version:' && npm --version && echo 'Current directory:' && pwd && echo 'All files before build:' && find . -name '*.png' -o -name 'img' -type d && npx nuxt generate && echo 'After build - checking for img:' && find . -name 'img' -type d && echo 'Checking .output structure:' && find .output -name 'img' -type d 2>/dev/null || echo 'No .output img found'"
  publish = ".output/public"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NUXT_TELEMETRY_DISABLED = "1"
  CI = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 