[build]
  command = "npx nuxt generate && echo 'Build complete, copying public assets...' && cp -r public/* .output/public/ && echo 'Assets copied, final structure:' && ls -la .output/public/ && echo 'Checking img directory:' && ls -la .output/public/img/"
  publish = ".output/public"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NUXT_TELEMETRY_DISABLED = "1"
  CI = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 