[build]
  command = "npx nuxt generate && echo 'Generated structure:' && find .output/public -type f | head -20 && echo 'Looking for img directory:' && find .output/public -name 'img' -type d && echo 'Copying nested public if exists:' && if [ -d '.output/public/public' ]; then cp -r .output/public/public/* .output/public/ && rm -rf .output/public/public; fi && echo 'Final check for img:' && ls -la .output/public/img/ || echo 'No img directory found'"
  publish = ".output/public"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NUXT_TELEMETRY_DISABLED = "1"
  CI = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 